name: caller_info
version: 0.0.5
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Caller info (frame, source, caller, line number)
homepage: https://github.com/mezoni/caller_info
dev_dependencies:
  unittest: any
