name: caller_info
version: 0.0.9
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Caller info (caller, closure, file, frame, line, method, source, type).
homepage: https://github.com/mezoni/caller_info
dependencies:
  path: any
dev_dependencies:
  unittest: any
